language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer selfupdate
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --exclude-group functional

after_script:
  - vendor/bin/coveralls

notifications:
  email: matthiasnoback@gmail.com
